import TopNav from './Component/TopNav.jsx'
import './globals.css'


export const metadata = {
  title: 'Home',
  description: 'Generated by NKY',
}

export default function Layout() {
  return (
    <html lang="en">
      <body><TopNav/></body>
    </html>
  )
}
